"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: csl_pineapple.msg.dds_
  IDL file: MotorStates_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MotorStates_(idl.IdlStruct, typename="csl_pineapple.msg.dds_.MotorStates_"):
    states: types.sequence['csl_sdk2py.idl.csl_pineapple.msg.dds_.MotorState_'] = field(default_factory=lambda: [])


