"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: csl_pineapple.msg.dds_
  IDL file: MotorCmds_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MotorCmds_(idl.IdlStruct, typename="csl_pineapple.msg.dds_.MotorCmds_"):
    cmds: types.sequence['csl_sdk2py.idl.csl_pineapple.msg.dds_.MotorCmd_'] = field(default_factory=lambda: [])


