"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: csl_pineapple.msg.dds_
  IDL file: TimeSpec_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types



@dataclass
@annotate.final
@annotate.autoid("sequential")
class TimeSpec_(idl.IdlStruct, typename="csl_pineapple.msg.dds_.TimeSpec_"):
    sec: types.int32
    nanosec: types.uint32


